config/routes.rb
Rails.application.routes.draw do
  
  root 'top#index'
  resources :assets,  only: [:index, :new]
  resources :system_configs, only: [:index, :edit, :update]
  resources :balanceclasses, only: [:create, :destroy]
  resources :balances, only: [:index, :new, :create, :destroy] do
    collection do
      get 'add'
      post 'bulk_create'
    end
  end

  post '/callback' => 'webhook#callback'
  

end

app/models/system_config.rb
class SystemConfig < ActiveRecord::Base
end

app/controllers/system_configs_controller.rb
class SystemConfigsController < ApplicationController
  
  def index
    
    # 月の開始日に必要な変数
    @start_date = SystemConfig.find_by(:name => 'start_date')
    @day = []
    for i in 1..31 do 
      @day.push [i, "#{i}"]
    end
    
    # 分類登録に必要な変数
    @balance_classes = BalanceClass.all
    @new_balanceclass = BalanceClass.new
  end
  
  def update
    systemconfig = SystemConfig.find(params[:id])
    systemconfig.value = systemconfig_params[:value]
    if systemconfig.save
      redirect_to root_path, notice: '変更しました'
    else
      redirect_to root_path, notice: '変更に失敗しました'
    end
  end
  
  private
    def systemconfig_params
      params.require(:system_config).permit(:value, :name)
    end
end

app/helpers/system_configs_helper.rb
module SystemConfigsHelper
end

app/views/system_configs/index.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron text-center">
      <h1>システム設定</h1>
    </div>
    <div class="col-xs-12">
      <h1>開始日の設定</h1>
      何日から何日までを1か月とするかを設定します。<br>
      現在の開始日は <b><%= @start_date.value.to_i %>日</b> です
      <%= form_for(@start_date) do |f| %>
        <h4>開始日:<%= f.select :value, @day, :class => 'form form-horizontal' %></h4>
        <%= f.submit '開始日の変更', :method => 'patch' , :class => 'btn btn-primary' %>
      <% end %>
    </div>
    
    <div class="col-xs-12">
      <br>
      <h1>収支の分類設定</h1>
      収支を入力する際に設定する分類を登録します。現在の登録内容は以下の通りです。
      <table class="table table-bordered">
        <tr class="info">
          <th>収/支</th>
          <th>分類</th>
          <th>削除</th>
        </tr>
        <% @balance_classes.each do |balance| %>
          <tr>
            <td>
              <% if balance.balance_type == true %>
                収入
              <% else %>
                支出
              <% end %>
            </td>
            <td><%= balance.balance_class %></td>
            <td><%= link_to '削除',  balanceclass_path(balance.id), :method => 'delete' %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-xs-12">
      <h4>新しく分類を登録する</h4>
      <%= form_for(@new_balanceclass, :url => balanceclasses_path ) do |f| %>
        <table class="table table-hover">
          <tr>
            <th>収/支</th>
            <th>分類</th>
          </tr>
          <tr>
            <td><%= f.select :balance_type, [['収入', true],['支出', false]] %></td>
            <td><%= f.text_field :balance_class, :class => 'form-control' %></td>
          </tr>
        </table>
        <%= f.submit '分類の登録', :method => 'post', :class => 'btn btn-primary' %>
        <%= link_to 'TOP', root_path,  :class => 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>