config/routes.rb
Rails.application.routes.draw do
  
  root 'top#index'
  resources :assets,  only: [:index, :new]
  resources :system_configs, only: [:index, :edit, :update]
  resources :balanceclasses, only: [:create, :destroy]
  resources :balances, only: [:index, :new, :create, :destroy] do
    collection do
      get 'add'
      post 'bulk_create'
    end
  end

  post '/callback' => 'webhook#callback'
  

end

app/models/balance.rb
class Balance < ActiveRecord::Base
  validates :column, :value, :balance_class,  presence: true
  validates :value, numericality: true
  
  before_save :balance_class_find_or_create
  # 分類が存在しなければ登録する(Lineから登録される場合を想定)
  def balance_class_find_or_create
    balanceclass = self.balance_class
    BalanceClass.find_or_create_by(:balance_class => balanceclass) do |bc|
      bc.balance_type = self.balance_type
    end
  end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  
  def index
    # ユーザによって表示期間が指定された場合はその期間のデータを元に表示
    if period_params[:start_date] && period_params[:end_date]
    
      start_date = Date.parse(period_params[:start_date])
      end_date = Date.parse(period_params[:end_date])
      # 今月の支出状況作成
      @this_month_balances, @period_start, @period_end = self.class.helpers.get_period_balance(start_date,end_date)
      @summary = self.class.helpers.calc_this_month_summary(@this_month_balances)
      
    # period_paramsが空なら、標準の(システム設定で規定された)1か月間のデータを元に表示
    else
      
      # 収支状況を表示する期間(設定パラメータを取得)
      start_date = SystemConfig.find_by(:name => 'start_date').value.to_i.ordinalize
      
      # 今月の支出状況作成
      @this_month_balances, @period_start, @period_end = self.class.helpers.get_this_month_balance(start_date)
      @summary = self.class.helpers.calc_this_month_summary(@this_month_balances)
      
    end
    
    # 棒グラフ
    @bar_graph = LazyHighCharts::HighChart.new('column', :style => 'float:left;height:500px;width:500px;') do |f|
      
      # 横軸のラベル
      f.xAxis(categories: ['収入','支出'])
      
      # 棒グラフの収入の部分
      f.series(:name => '給料', :data => [@summary[:income],])
      
      # 棒グラフの支出の部分
      @summary[:balance_class_sum].each do |bc|
        f.series(:name => bc[0], :data => [0,bc[1]])
      end
      
      f.options[:chart][:defaultSeriesType] = 'column'
      f.plot_options({:column => {stacking: 'normal'}})
    end
    
    ## 後から追加する機能：支出の分類を円グラフで表示
    @pie_graph = LazyHighCharts::HighChart.new('pie', :style => 'float:left;height:500px;width:500px;') do |f|
      f.chart({defaultSeriesType: 'pie'})
      f.series({
        type: 'pie',
        name: '金額',
        data: @summary[:balance_class_sum].to_a
      })
    end
  end
  
  def new
    @balance = Balance.new
  end
  
  
  ### 一括登録する時に入力欄を追加するアクション
  def add
    @balance = Balance.new
  end
  
  ### 一括登録するアクション
  def bulk_create
    balances = params.require(:balances).map{ |balance| balance.permit(:value, :column, :subject, :balance_type, :balance_date, :balance_class) }
    balances.each do |b|
      Balance.create b
    end
    redirect_to root_path
  end
  
  ### 1つだけ登録するアクション(TOPページ経由)
  def create
    balance = Balance.new(balance_params)
    
    # 保存
    if balance.save
      redirect_to root_path, notice: '支出を登録しました'
    else
      redirect_to root_path, alert: '登録に失敗しました'
    end
  end
  
  def destroy
    balance = Balance.find(params[:id])
    balance.delete
    redirect_to balances_path, notice: '削除しました'
  end
  
  private
    def balance_params
      params.fetch(:balance, {}).permit(:value, :column, :subject, :balance_type, :balance_date, :balance_class)
    end
    
    def period_params
      params.permit(:start_date, :end_date)
    end
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/views/balances/_form.html.erb
<% id = "remove_#{Time.now.to_i}_#{Time.now.usec.to_i}" %>
<tr>
<%= fields_for "balances[]", @balance, index: nil do |f| %>
  <td><%= f.select :balance_type, [["収入", true ], ["支出", false ]], :class => 'form-horizontal' %></td>
  <td><%= f.number_field :value, :class => 'form-control' %></td>
  <td><%= f.date_field :balance_date , :value => Date.today , :class => 'form-control' %></td>
  <td><%= f.text_field :column , :class => 'form-control' %></td>
  <td><%= f.collection_select :balance_class, BalanceClass.all, :balance_class, :balance_class %></td>
  <td><%= f.text_area :subject , :class => 'form-control' %></td>
  <% end %>
  
  <!-- 削除リンク -->
  <td><%= link_to '1行削除', '', id: id , :class => 'btn btn-danger' %></td>
</tr>

<%= javascript_tag do %>
  $(document).ready(function(e){
    $('#<%= id %>').click(function(e){
      e.preventDefault();
      $(this).parent().parent().remove();
      return false
    });
  })
<% end %>

app/views/balances/add.js.erb
$("#balances_input_form").append("<%= j(render 'form') %>")

app/views/balances/index.html.erb
<div class="container">
  <div class="row">
    <div class="jumbotron text-center j-top">
      <h1>収支管理</h1>
    </div>
    <p>表示期間: <%= @period_start.strftime('%Y-%m-%d') %> ~ <%= @period_end.strftime('%Y-%m-%d') %></p>
    
    <br>
    <p>表示期間を変更して再表示</p>
    <br>
    <%= form_tag(balances_path, method: 'get' ) do %>
      開始日<%= date_field_tag :start_date , Date.today - 2.month %>
      終了日<%= date_field_tag :end_date , Date.today - 1.month %>
      <%= submit_tag '期間を変えて表示',  :class => 'btn btn-primary' %>
    <% end %>
    
    <!-- 収支をjumbotronで表示する部分-->
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-4">
          <div class="jumbotron text-center j-income">
            収入
            <br><p><%= @summary[:income] %>円</p>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="jumbotron text-center j-payment">
            支出
            <br><p><%= @summary[:payment] %>円</p>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="jumbotron text-center j-total">
            <b>収支</b>
            <br><p><b><%= @summary[:income] - @summary[:payment] %>円</b></p>
          </div>
        </div>
      </div>
    </div>
    
    <!-- 収支の分析(グラフ)の表示 -->
    <div class="col-xs-12">
      <h2>収支分析</h2>
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <%= high_chart('bar', @bar_graph) %>
        </div>
        <div class="col-xs-12 col-md-6">
          <%= high_chart('pie', @pie_graph) %>
        </div>
      </div>
    </div>
    
    <!-- 収支の項目を1つずつ表示する部分 -->
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-12">
          <h2>収支の詳細</h2>
          <table class='table table-hover table-bordered'>
            <tr class='info'>
              <th>日付</th>
              <th>収/支</th>
              <th>使途</th>
              <th>分類</th>
              <th>金額</th>
              <th>削除</th>
            </tr>
            <% @this_month_balances.each do |balance| %>
              <tr>
                <td><%= balance.balance_date %></td>
                <% if balance.balance_type == false %>
                  <td>支出</td>
                <% else %>
                  <td>収入</td>
                <% end %>
                <td><%= balance.column %></td>
                <td><%= balance.balance_class %></td>
                <td><%= balance.value %></td>
                <td><%= link_to '削除', balance_path(balance.id), :method => 'delete' %></td>
                <!-- ### balance_type == false なら 支出 ### -->
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>

    <div class="col-xs-12">
      <%= link_to '新規登録', new_balance_path, :class => 'btn btn-primary' %>
      <%= link_to 'TOP', root_path, :class => 'btn btn-default' %>
    </div>
    
  </div>
</div>

app/views/balances/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>収支の登録</h1>
      <%= link_to '1行追加', add_balances_path, remote: true, :class => 'btn btn-default' %>
      <br>
      <%= form_tag bulk_create_balances_path do %>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>収/支</th>
              <th>金額</th>
              <th>日付</th>
              <th>使途</th>
              <th>分類</th>
              <th>備考</th>
              <th>削除</th>
            </tr>
          </thead>
          <tbody id="balances_input_form">
            <%= render 'form' %>
          </tbody>
        </table>
        <%= submit_tag '収支の登録' , :method => 'post', :class => 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>