config/routes.rb
Rails.application.routes.draw do
  
  root 'top#index'
  resources :assets,  only: [:index, :new]
  resources :system_configs, only: [:index, :edit, :update]
  resources :balanceclasses, only: [:create, :destroy]
  resources :balances, only: [:index, :new, :create, :destroy] do
    collection do
      get 'add'
      post 'bulk_create'
    end
  end

  post '/callback' => 'webhook#callback'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kakeibo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <!-- ロゴ。アプリ名が決まらないので今回は消しておく -->
          <%#= link_to root_path do %>
            <%#= image_tag('mylogo_white.png') %>
          <%# end %>
          
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "TOP", root_path , :class => 'mycssclass' %></li>
            <li><%= link_to "設定", system_configs_path, :class => 'mycssclass' %></li>
            <li><%= link_to "収支管理", balances_path, :class => 'mycssclass' %></li>
            <!--<li><%= link_to "資産管理", assets_path , :class => 'mycssclass' %></li>-->
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>

<%= yield %>
  <footer>
    <p>村田家の家計簿 2017 Copyright K.M</p>
  </footer>
</body>
</html>